### ISSUE TITLE
Disable caching or forcing update

### ISSUE THREAD

**Issue by jhillairet** [piScope/piScope#30]
Once a pulse has been made in WEST, the data are available but on a temporary time base (the 'IGNITRON' time code is not available). So we need to wait for few minutes after the pulses in order to see the final time base. However, if I loaded the pulse too quickly, clicking on "apply" again will not update the data. 

Is it possible to disable the cache in piScope/wscope ? Or to force reloading data ?

**Comment by sshiraiwa** [comment]
Yes, the default action of scope is if there is a plot object associated with the shot
number you are loading, it simply reuse the plot data.  This is meant to reduce
the network data access, but it fools you in your use case. Please try,,,

1) In the scope window, right click the apply button and select “Update all"
or
2) Use Scope -> Tools -> Reset MDS workers

Please let us know if it works. If not I will check how this code section was implemented.

Also,  in a longer time, you could broadcast a signal to notify that the data is updated on the
data server. Scope can receive MDSplus event. If you can generate it, it would be the easiest.

**Comment by jhillairet** [comment]
Solution 1 works. I wasn't aware of the right button click ;) 

Thanks.
