### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by jmilhone** [piScope/piScope#42]
I was curious if you have planned python 3 support since python 2 will officially not be supported on January 1, 2020. I was unable to simply convert the project using the 2to3 utility because of complicated relative and absolute imports.

**Comment by jhillairet** [comment]
Some time ago I've tried to migrate piScope to Python 3 and at that time, the main challenge was wxPython which was only Python 2. Since wxPython 4.0, it should no more be a problem, and indeed more a challenge with proper importation order.

**Comment by sshiraiwa** [comment]
Thank you for the input. I am going to start the migration work soon before the hot summer comes. From my perspective, I need to migrate PyMFEM (https://github.com/mfem/PyMFEM), Petra-M (https://github.com/piScope/PetraM_Base) all together. So, this will take a fair amount of efforts.
Do you have any suggestions about the 2 to 3 migration tool, tutorial?

**Comment by jmilhone** [comment]
There is documentation for 2to3 here (https://docs.python.org/2/library/2to3.html). 

The simplest use case is:
`2to3 -w path_to_project_folder`

It should write over all files and produce backup files. I did run this on piScope/python and it seemed to work great. After doing that though, I couldn't figure out how to fix the imports.

**Comment by sshiraiwa** [comment]
Thanks. I just did 2to3, autopep8, and a few edits. So far I noticed...

* import is indeed an issue (perhaps I should count relative import first, and make same auto fixer)
* str has __iter__ method (can not use this to distinguish str from tuple, list)
* unicode needs to be encoded (not equal to byte)

I will see how long does it take to finish...;D

**Comment by jhillairet** [comment]
I would recommend migration steps by steps, using 2to3 few times with only
specific conversion options. Like print->print() only, then commit. Repeat
with the other python 3 changes (except,  range, etc).
Up a certain point, most can be tested under python 2, which simplify
debugging.

**Comment by sshiraiwa** [comment]
Thank you for the advice. I was not aware 2to3 is actually one-way migration tool. So it brakes the code in PY2. I did start over and continue to see how it goes in py37_prep branch.

**Comment by jhillairet** [comment]
Found the following tutorial in the latest Python Weekly : https://www.youtube.com/watch?v=9pxv6h7DU4w ;)

**Comment by sshiraiwa** [comment]
Thank you. I pushed py37_prep2 to here, but please don't bother downloading it yet. It doesn't even load data from MDSplus yet. I will keep posting the status here.

**Comment by jhillairet** [comment]
Hello,

Is the piscope fully OK for Python3? I run into a trouble with `TreeDict` package, which seems outdated and can't be installed with pip3. 

```
Process MDSMPDirectWorker-5:
Traceback (most recent call last):
  File "/Home/JH218595/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Home/JH218595/piScope/python/ifigure/mdsplus/mds_mpth_directworker.py", line 115, in run
    DirectWorkerBase.run_loop(self, self.translater, *args, **kargs)
  File "/Home/JH218595/piScope/python/ifigure/mdsplus/mds_mpth_directworker.py", line 23, in run_loop
    task = self.task_queue.get(True)
  File "/Home/JH218595/anaconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/Home/JH218595/piScope/python/ifigure/mdsplus/fig_mds.py", line 32, in <module>
    from ifigure.mto.treedict import TreeDict
  File "/Home/JH218595/piScope/python/ifigure/mto/treedict.py", line 39, in <module>
    import ifigure.events
  File "/Home/JH218595/piScope/python/ifigure/events.py", line 18, in <module>
    from ifigure.widgets.book_viewer import BookViewer
  File "/Home/JH218595/piScope/python/ifigure/widgets/book_viewer.py", line 38, in <module>
    from ifigure.widgets.canvas.ifigure_canvas import ifigure_canvas
  File "/Home/JH218595/piScope/python/ifigure/widgets/canvas/ifigure_canvas.py", line 55, in <module>
    from ifigure.widgets.navibar2 import navibar
  File "/Home/JH218595/piScope/python/ifigure/widgets/navibar2.py", line 9, in <module>
    from ifigure.mto.fig_axes import FigInsetAxes
  File "/Home/JH218595/piScope/python/ifigure/mto/fig_axes.py", line 36, in <module>
    from ifigure.mto.fig_obj import FigObj
  File "/Home/JH218595/piScope/python/ifigure/mto/fig_obj.py", line 24, in <module>
    from ifigure.mto.treedict import TreeDict
ImportError: cannot import name 'TreeDict'
('cancelled jobs', [])
```

**Comment by sshiraiwa** [comment]
I am bit confused. TreeDict is a part of piScope and one of foundation class to
manage project data structure. If it cannot load it, it should be causing the error much earlier.
