### ISSUE TITLE
Simulations with a fine mesh

### ISSUE THREAD

**Issue by kunalsanwalka** [piScope/piScope#52]
Simulations on the Cori cluster with a mesh size of <5cm still do not seem to work properly. A failed run is stored on the cluster under-
/global/homes/k/ksanwalk/myscratch/mfem_batch/LAPD_freq_325KHz_uniformRef/

It seems to be an issue with the MUMPS solver.

Is there a way for me to try and create a finer mesh on the server side? I noticed that under the mesh tab in the model tree there are 2 options labelled-
1. DomainRefinement
2. UniformRefinement

I am wondering what is the proper procedure to use these options and if there is a difference between using this feature and generating a finer mesh from scratch.

-Kunal Sanwalka
(kunalsanwalka@g.ucla.edu)

**Comment by sshiraiwa** [comment]
Hi Kunal. 

You can add UniformRefinement/DomainRefinement next to the MfemMesh using the model project editor. UniformRefinement performs mfem::mesh::UniformRefinement. Domain refinement is similar to UniformRefinement but it restricts the refinement in a certain domain. Please note that, for 3D RF problem, one UniformRefinement increases the degree of freedoms by 6 to 8. 

A major difference is that these are refinement at the mesh level, It does not look how the original geometry is parametrized. 

Having this said, I am not sure if these feature helps your case. Sorry for being late. Regarding your original issue, I would propose to discuss off-line.

**Comment by kunalsanwalka** [comment]
Dear Syun'ichi,

Thank you for the reply.

We were thinking that since the solver only has an issue when the entire plasma is meshed below 5cm, perhaps it would be possible to add a radially smaller cylinder coaxial to the main plasma domain which can have a finer mesh. Perhaps this would allow us to circumvent the issue with MUMPS as it does not seem to have a problem with certain domains having a finer mesh (for example, the antenna has a mesh of 1mm).

(I will update this post with the directory of this new geometry once the login problems are sorted)

As for the discussion, when are you available to have it? I am available to talk all of next week. Please let me know what time works best for you.

Regards,
Kunal Sanwalka
