### ISSUE TITLE
Option missing under the mesh tab in the model tree

### ISSUE THREAD

**Issue by kunalsanwalka** [piScope/piScope#53]
Dear Syun'ichi,

When developing the model for Gurleen, I noticed that the option to add a 'MeshGroup' has been removed from the 'Mesh' tab and instead been replaced with 'MFEMMesh', See screenshots below-

![image](https://user-images.githubusercontent.com/45079569/74181522-564ac480-4bf6-11ea-98d9-6a219ae1d0e5.png)

![image](https://user-images.githubusercontent.com/45079569/74181576-6e224880-4bf6-11ea-84fa-71459eb31158.png)

1. Is there a significant difference between the 2 options? 
2. Has the same option been renamed?
3. Should all older model trees using the 'MeshGroup' option switch over to 'MFEMMesh' or stick to the older implementation?

Regards,
Kunal Sanwalka

**Comment by sshiraiwa** [comment]
These two are the same. MFEMmesh represents better what this branch is supposed to do. It defines how the MFEM mesh being used in the simulation is created.
