### ISSUE TITLE
Setting a coax boundary condition 

### ISSUE THREAD

**Issue by gkbal** [piScope/piScope#54]
I am currently setting up the physics for my RF antenna model in the LAPD using petra-m and I have some questions about the coax boundary condition. 
1) What is the difference between TEM vs. TEM coax mode in the Port configuration? Which of these options would you recommend i use?
2) what is the m/n value?
3) What is epsilonr and mur for a port? I assumed that these parameters would already be set by the domain tab. 

My project file is located at -
home/gurleenkbal/Documents/Petram_SSRFantenna/SSRFantennaTom2.pfz
![image](https://user-images.githubusercontent.com/41760499/74385224-11bf5480-4dc1-11ea-9fe5-b85c145148a2.png)

**Comment by sshiraiwa** [comment]
Please use TEM-coax. TEM is for the wave injection in two parallel metal plate.
m/n does not matter for coax. Please set the same epsilonr and mur from the
domain setting. You are right that in principle it should read these information 
from the domain panel, but it does not do it yet.

—
S

**Comment by gkbal** [comment]
Got it. Thank you!
