### ISSUE TITLE
Queue Error

### ISSUE THREAD

**Issue by gkbal** [piScope/piScope#58]
I was able to create a directory on eofe7 computer for my petram simulation. The directory is located at-
/home/gurleenkbal/myscratch/mfem_batch/2020_03_10_RF_SS_2cmMesh

But when I try to submit the job, I get a Queue error- "failed to read queue config". 
![QueueIssue](https://user-images.githubusercontent.com/41760499/76350771-9373a680-62c9-11ea-85a0-a5dc49eaf0e6.png)

Additionally, this error persisted when I tried to use one of Kunal's files (which we know he was able to submit to the cluster). We changed the user name under the connections tab in piscope to my username.
![QueueIssue2](https://user-images.githubusercontent.com/41760499/76350902-c9188f80-62c9-11ea-87c8-4a32006b1489.png)

The piscope file that I'm trying to submit is on the local workstation (mfews02)-
gurleenkbal/Documents/Petram_SSRFantenna/SSRFantennaTom5.pfz

**Comment by sshiraiwa** [comment]
Hi Gurleen, 

To submit a job to our cluster, please take a look at our wikipage.

**Comment by sshiraiwa** [comment]
@gkbal 
I will close this for now. Please feel free to reopen it if you have further issue in job submission
