### ISSUE TITLE
Feature Request: Combine directory creation and job submission screens

### ISSUE THREAD

**Issue by kunalsanwalka** [piScope/piScope#61]
Problem: Currently to submit a job one has to create a directory on the cluster and specify the job parameters on 2 separate windows. That is, we first have to use this window to create the directory-
![image](https://user-images.githubusercontent.com/45079569/77689504-fec2a700-6f5e-11ea-84c0-7f562ea1b5d4.png)

And then this one to specify job submission parameters-
![image](https://user-images.githubusercontent.com/45079569/77689518-04b88800-6f5f-11ea-8067-87f7b058c1a0.png)

This leads to ambiguity regarding which directory one is submitting a particular job to since we cannot see it on the job submission window. For example, when submitting multiple jobs for a frequency sweep, one can forget if the directory was created before the job is submitted.

Proposed solution: If we combine the 2 windows so that the directory is created and job submitted in one action, it will reduce the probability of errors and the time taken to submit jobs. A possible job submission window could look like-

********** ********** ********** ********** **********
Enter remote directory name: __________
Number of Nodes: __________
Number of Cores (total): __________
Number of OpenMP threads: __________
Wall Clock: __________
Queue: __________
Skip Sending Mesh File: __________
********** ********** ********** ********** **********

**Comment by sshiraiwa** [comment]
![Screen Shot 2020-04-14 at 5 43 45 PM](https://user-images.githubusercontent.com/1929159/79277315-91c47200-7e77-11ea-8831-a892ff37808a.png)
