### ISSUE TITLE
Unable to open project in NoMachine

### ISSUE THREAD

**Issue by kunalsanwalka** [piScope/piScope#63]
I am unable to open my project on NoMachine via the terminal window, The message I receive is-

(20190713_py3)mfews01:~ sanwalka$ piscope -d
/home/shiraiwa/twopi_roots/20190713_py3/src/piScope/bin/piscope.sh
reading extra color maps
debug mode (redirect is suppressed)
DEBUG(BackendWXAggGL)::loading glcanvas12
checking file contents...
done....(load)
initializing model...
done....(init) ProjectTop(proj)
DEBUG(BookViewer)::_force_layout
DEBUG(iFigureApp)::checking HG repo for updates
DEBUG(Engine 0):: Loading mesh (serial)
DEBUG(GeomModel 0):: gmsh file path /home/sanwalka/.piscope_tmp/piscope_sanwalka/mfews01.pid30424/.###ifigure_home_sanwalka_test_geom_fullChamber.pfz/proj/model1/mfem/GmshMesh1.msh
/home/shiraiwa/twopi_roots/20190713_py3/bin/piscope: line 88: 30424 Killed                  $INTERPRETER $APP $EXTRA $EXTRA2 $EXTRA3 $EXTRA4 $EXTRA5 -r $COM $1

I have tried to overwrite the file with one I know works, yet it does not seem to solve the issue.

The project I am trying to open is located at the following address-
/home/sanwalka/test_geaom_fullchamber.pfz

**Comment by sshiraiwa** [comment]
Can you try terminating NoMachine and open it again. I got the same error first, but
now after recreating a new session from scratch, it opens the file properly.

—
S

**Comment by kunalsanwalka** [comment]
It seems to work now, I had tried to terminate and reopen NoMachine to fix the issue before to no avail. However it seems to have worked this time.

Thank you for your help.

Regards,
Kunal Sanwalka
